### ISSUE TITLE
传入较大的 unfocusedCount（比如 20）和 count（如150） 后，样式错乱

### ISSUE THREAD

**Issue by mariohide** [zj565061763/compose-wheel-picker#2]
https://github.com/zj565061763/compose-wheel-picker/assets/20430813/49b6b1b8-fce7-4096-9136-e52407871df7

**Comment by zj565061763** [comment]
不好意思，最近比较忙，这个问题在[1.0.0-rc01](https://github.com/zj565061763/compose-wheel-picker/releases/tag/1.0.0-rc01)已经修复
