### ISSUE TITLE
快速滑动时内容显示有延迟

### ISSUE THREAD

**Issue by xxxape** [zj565061763/compose-wheel-picker#3]
https://github.com/zj565061763/compose-wheel-picker/assets/49482531/f815ae12-da0a-4055-ac00-db537fc3c250

快速滑动的时候内容会延迟加载出来，慢慢滑是正常的，请问这个应该怎么解决呢？

**Comment by zj565061763** [comment]
可以提供一个项目demo吗？我用来排查一下

**Comment by xxxape** [comment]
我自己找到原因了，我设置了三级透明度，区间外的设置了 0，导致快速滑动的时候，其他的透明度还是 0，所以都看不到···
![screenshot-20240614-185311](https://github.com/zj565061763/compose-wheel-picker/assets/49482531/6346c41e-f857-42be-be83-501513349026)
